# Generated by Django 5.1.2 on 2024-10-24 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('element_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('img_url', models.CharField(max_length=50, null=True)),
                ('pass_time', models.CharField(max_length=30)),
                ('atomic_mass', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Decay',
            fields=[
                ('decay_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_formation', models.DateTimeField(null=True)),
                ('date_of_finish', models.DateTimeField(null=True)),
                ('pass_time', models.CharField(max_length=30, null=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_decays', to=settings.AUTH_USER_MODEL)),
                ('moderator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator_decays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Element_Decay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=30, null=True)),
                ('decay_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decay_elements', to='radioactive_elements_app.element')),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_decays', to='radioactive_elements_app.element')),
            ],
            options={
                'unique_together': {('element_id', 'decay_id')},
            },
        ),
    ]
