# Generated by Django 5.1.2 on 2024-10-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0002_alter_element_pass_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='img_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='pass_time',
            field=models.CharField(max_length=100),
        ),
    ]
