# Generated by Django 5.1.2 on 2024-10-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0003_alter_element_img_url_alter_element_pass_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='pass_time',
            new_name='period_time_text',
        ),
    ]
