# Generated by Django 5.1.2 on 2024-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0004_rename_pass_time_element_period_time_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decay',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='decay',
            old_name='moderator_id',
            new_name='moderator',
        ),
        migrations.AlterField(
            model_name='decay',
            name='status',
            field=models.CharField(choices=[('draft', 'черновик'), ('deleted', 'удален'), ('completed', 'завершен'), ('formed', 'сформирован'), ('rejected', 'отклонен')], max_length=20),
        ),
    ]
