# Generated by Django 5.1.2 on 2024-10-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0006_alter_decay_date_of_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element_decay',
            name='decay_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decay_elements', to='radioactive_elements_app.decay'),
        ),
    ]
