# Generated by Django 5.1.2 on 2024-10-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0007_alter_element_decay_decay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='decay',
            name='remaining_quantity',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
