# Generated by Django 5.1.2 on 2024-10-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0008_decay_remaining_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element_decay',
            old_name='decay_id',
            new_name='decay',
        ),
        migrations.RenameField(
            model_name='element_decay',
            old_name='element_id',
            new_name='element',
        ),
    ]
