# Generated by Django 5.1.2 on 2024-11-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0009_rename_decay_id_element_decay_decay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='status',
            field=models.CharField(choices=[('active', 'действует'), ('deleted', 'удален')], max_length=20),
        ),
    ]
