# Generated by Django 5.1.2 on 2024-11-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0010_alter_element_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decay',
            name='remaining_quantity',
        ),
        migrations.AddField(
            model_name='element_decay',
            name='remaining_quantity',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
