# Generated by Django 5.1.2 on 2024-11-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0012_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='period_time',
            field=models.FloatField(default=0),
        ),
    ]
