# Generated by Django 5.1.2 on 2024-11-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0014_customuser_delete_authuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=254, verbose_name='Пароль'),
        ),
    ]
