# Generated by Django 5.1.2 on 2025-02-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0015_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='decay',
            name='qr',
            field=models.TextField(null=True),
        ),
    ]
