# Generated by Django 5.1.2 on 2025-02-14 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0016_decay_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=30, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attrubute_elements', to='radioactive_elements_app.attribute')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_attributes', to='radioactive_elements_app.element')),
            ],
        ),
    ]
