# Generated by Django 5.1.2 on 2025-02-14 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioactive_elements_app', '0017_attribute_attribute_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute_element',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attribute_elements', to='radioactive_elements_app.attribute'),
        ),
        migrations.AlterField(
            model_name='attribute_element',
            name='value',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
